// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: protobuf/v1/account.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AccountServiceClient is the client API for AccountService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AccountServiceClient interface {
	AuthAccount(ctx context.Context, in *CredentialsRequest, opts ...grpc.CallOption) (*AccountReply, error)
	GetAccountDetails(ctx context.Context, in *AccountDetailRequest, opts ...grpc.CallOption) (*AccountDetailReply, error)
	ValidateProfile(ctx context.Context, in *ValidateProfileRequest, opts ...grpc.CallOption) (*GenericReply, error)
	GetConciseProfile(ctx context.Context, in *ConciseProfileRequest, opts ...grpc.CallOption) (*ConciseProfileReply, error)
}

type accountServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAccountServiceClient(cc grpc.ClientConnInterface) AccountServiceClient {
	return &accountServiceClient{cc}
}

func (c *accountServiceClient) AuthAccount(ctx context.Context, in *CredentialsRequest, opts ...grpc.CallOption) (*AccountReply, error) {
	out := new(AccountReply)
	err := c.cc.Invoke(ctx, "/account.v1.AccountService/AuthAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) GetAccountDetails(ctx context.Context, in *AccountDetailRequest, opts ...grpc.CallOption) (*AccountDetailReply, error) {
	out := new(AccountDetailReply)
	err := c.cc.Invoke(ctx, "/account.v1.AccountService/GetAccountDetails", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) ValidateProfile(ctx context.Context, in *ValidateProfileRequest, opts ...grpc.CallOption) (*GenericReply, error) {
	out := new(GenericReply)
	err := c.cc.Invoke(ctx, "/account.v1.AccountService/ValidateProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) GetConciseProfile(ctx context.Context, in *ConciseProfileRequest, opts ...grpc.CallOption) (*ConciseProfileReply, error) {
	out := new(ConciseProfileReply)
	err := c.cc.Invoke(ctx, "/account.v1.AccountService/GetConciseProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountServiceServer is the server API for AccountService service.
// All implementations must embed UnimplementedAccountServiceServer
// for forward compatibility
type AccountServiceServer interface {
	AuthAccount(context.Context, *CredentialsRequest) (*AccountReply, error)
	GetAccountDetails(context.Context, *AccountDetailRequest) (*AccountDetailReply, error)
	ValidateProfile(context.Context, *ValidateProfileRequest) (*GenericReply, error)
	GetConciseProfile(context.Context, *ConciseProfileRequest) (*ConciseProfileReply, error)
	mustEmbedUnimplementedAccountServiceServer()
}

// UnimplementedAccountServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAccountServiceServer struct {
}

func (UnimplementedAccountServiceServer) AuthAccount(context.Context, *CredentialsRequest) (*AccountReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthAccount not implemented")
}
func (UnimplementedAccountServiceServer) GetAccountDetails(context.Context, *AccountDetailRequest) (*AccountDetailReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccountDetails not implemented")
}
func (UnimplementedAccountServiceServer) ValidateProfile(context.Context, *ValidateProfileRequest) (*GenericReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateProfile not implemented")
}
func (UnimplementedAccountServiceServer) GetConciseProfile(context.Context, *ConciseProfileRequest) (*ConciseProfileReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConciseProfile not implemented")
}
func (UnimplementedAccountServiceServer) mustEmbedUnimplementedAccountServiceServer() {}

// UnsafeAccountServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AccountServiceServer will
// result in compilation errors.
type UnsafeAccountServiceServer interface {
	mustEmbedUnimplementedAccountServiceServer()
}

func RegisterAccountServiceServer(s grpc.ServiceRegistrar, srv AccountServiceServer) {
	s.RegisterService(&AccountService_ServiceDesc, srv)
}

func _AccountService_AuthAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CredentialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).AuthAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.v1.AccountService/AuthAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).AuthAccount(ctx, req.(*CredentialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_GetAccountDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).GetAccountDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.v1.AccountService/GetAccountDetails",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).GetAccountDetails(ctx, req.(*AccountDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_ValidateProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).ValidateProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.v1.AccountService/ValidateProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).ValidateProfile(ctx, req.(*ValidateProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_GetConciseProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConciseProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).GetConciseProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.v1.AccountService/GetConciseProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).GetConciseProfile(ctx, req.(*ConciseProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AccountService_ServiceDesc is the grpc.ServiceDesc for AccountService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AccountService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "account.v1.AccountService",
	HandlerType: (*AccountServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AuthAccount",
			Handler:    _AccountService_AuthAccount_Handler,
		},
		{
			MethodName: "GetAccountDetails",
			Handler:    _AccountService_GetAccountDetails_Handler,
		},
		{
			MethodName: "ValidateProfile",
			Handler:    _AccountService_ValidateProfile_Handler,
		},
		{
			MethodName: "GetConciseProfile",
			Handler:    _AccountService_GetConciseProfile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protobuf/v1/account.proto",
}
