// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protofiles/search.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UpdateSearchResultResponse struct {
	Error                *Status  `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateSearchResultResponse) Reset()         { *m = UpdateSearchResultResponse{} }
func (m *UpdateSearchResultResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateSearchResultResponse) ProtoMessage()    {}
func (*UpdateSearchResultResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_89ac98895d227d00, []int{0}
}

func (m *UpdateSearchResultResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateSearchResultResponse.Unmarshal(m, b)
}
func (m *UpdateSearchResultResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateSearchResultResponse.Marshal(b, m, deterministic)
}
func (m *UpdateSearchResultResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateSearchResultResponse.Merge(m, src)
}
func (m *UpdateSearchResultResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateSearchResultResponse.Size(m)
}
func (m *UpdateSearchResultResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateSearchResultResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateSearchResultResponse proto.InternalMessageInfo

func (m *UpdateSearchResultResponse) GetError() *Status {
	if m != nil {
		return m.Error
	}
	return nil
}

type UpdateSearchResultRequest struct {
	Data                 map[string]*any.Any `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	UpdateType           string              `protobuf:"bytes,2,opt,name=updateType,proto3" json:"updateType,omitempty"`
	Args                 string              `protobuf:"bytes,3,opt,name=args,proto3" json:"args,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *UpdateSearchResultRequest) Reset()         { *m = UpdateSearchResultRequest{} }
func (m *UpdateSearchResultRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateSearchResultRequest) ProtoMessage()    {}
func (*UpdateSearchResultRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_89ac98895d227d00, []int{1}
}

func (m *UpdateSearchResultRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateSearchResultRequest.Unmarshal(m, b)
}
func (m *UpdateSearchResultRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateSearchResultRequest.Marshal(b, m, deterministic)
}
func (m *UpdateSearchResultRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateSearchResultRequest.Merge(m, src)
}
func (m *UpdateSearchResultRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateSearchResultRequest.Size(m)
}
func (m *UpdateSearchResultRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateSearchResultRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateSearchResultRequest proto.InternalMessageInfo

func (m *UpdateSearchResultRequest) GetData() map[string]*any.Any {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *UpdateSearchResultRequest) GetUpdateType() string {
	if m != nil {
		return m.UpdateType
	}
	return ""
}

func (m *UpdateSearchResultRequest) GetArgs() string {
	if m != nil {
		return m.Args
	}
	return ""
}

type Status struct {
	Code                 int32      `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string     `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Details              []*any.Any `protobuf:"bytes,3,rep,name=details,proto3" json:"details,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_89ac98895d227d00, []int{2}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Status) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Status) GetDetails() []*any.Any {
	if m != nil {
		return m.Details
	}
	return nil
}

func init() {
	proto.RegisterType((*UpdateSearchResultResponse)(nil), "search.v1.UpdateSearchResultResponse")
	proto.RegisterType((*UpdateSearchResultRequest)(nil), "search.v1.UpdateSearchResultRequest")
	proto.RegisterMapType((map[string]*any.Any)(nil), "search.v1.UpdateSearchResultRequest.DataEntry")
	proto.RegisterType((*Status)(nil), "search.v1.Status")
}

func init() { proto.RegisterFile("protofiles/search.proto", fileDescriptor_89ac98895d227d00) }

var fileDescriptor_89ac98895d227d00 = []byte{
	// 345 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0x4f, 0x4b, 0xeb, 0x40,
	0x14, 0xc5, 0x49, 0xd3, 0x3f, 0xe4, 0x96, 0x07, 0xef, 0x0d, 0x0f, 0x4c, 0xb3, 0x90, 0x12, 0x2a,
	0x16, 0xc1, 0x09, 0x8d, 0x1b, 0x71, 0x67, 0xb1, 0x4b, 0x37, 0x53, 0xdd, 0xb8, 0x9b, 0x36, 0xb7,
	0x31, 0x34, 0x66, 0xd2, 0x99, 0x49, 0x20, 0x5f, 0xd7, 0x4f, 0x22, 0x9d, 0x31, 0xa5, 0xa0, 0x45,
	0x77, 0xf7, 0xce, 0x39, 0xf3, 0x9b, 0x7b, 0xcf, 0xc0, 0x59, 0x29, 0x85, 0x16, 0x9b, 0x2c, 0x47,
	0x15, 0x29, 0xe4, 0x72, 0xfd, 0x4a, 0xcd, 0x09, 0xf1, 0x3e, 0xbb, 0x7a, 0x16, 0x8c, 0x52, 0x21,
	0xd2, 0x1c, 0x23, 0x23, 0xac, 0xaa, 0x4d, 0xc4, 0x8b, 0xc6, 0xba, 0xc2, 0x05, 0x04, 0xcf, 0x65,
	0xc2, 0x35, 0x2e, 0x8d, 0x9b, 0xa1, 0xaa, 0x72, 0xcd, 0x50, 0x95, 0xa2, 0x50, 0x48, 0x2e, 0xa1,
	0x87, 0x52, 0x0a, 0xe9, 0x3b, 0x63, 0x67, 0x3a, 0x8c, 0xff, 0xd1, 0x03, 0x93, 0x2e, 0x35, 0xd7,
	0x95, 0x62, 0x56, 0x0f, 0xdf, 0x1d, 0x18, 0x7d, 0xc7, 0xd9, 0x55, 0xa8, 0x34, 0x99, 0x43, 0x37,
	0xe1, 0x9a, 0xfb, 0xce, 0xd8, 0x9d, 0x0e, 0x63, 0x7a, 0x44, 0x39, 0x79, 0x87, 0x3e, 0x70, 0xcd,
	0x17, 0x85, 0x96, 0x0d, 0x33, 0x77, 0xc9, 0x39, 0x40, 0x65, 0xcc, 0x4f, 0x4d, 0x89, 0x7e, 0x67,
	0xec, 0x4c, 0x3d, 0x76, 0x74, 0x42, 0x08, 0x74, 0xb9, 0x4c, 0x95, 0xef, 0x1a, 0xc5, 0xd4, 0xc1,
	0x23, 0x78, 0x07, 0x0c, 0xf9, 0x0b, 0xee, 0x16, 0x1b, 0xb3, 0x89, 0xc7, 0xf6, 0x25, 0xb9, 0x82,
	0x5e, 0xcd, 0xf3, 0xca, 0xd2, 0x86, 0xf1, 0x7f, 0x6a, 0x63, 0xa2, 0x6d, 0x4c, 0xf4, 0xbe, 0x68,
	0x98, 0xb5, 0xdc, 0x75, 0x6e, 0x9d, 0x70, 0x03, 0x7d, 0xbb, 0xf5, 0xfe, 0xb1, 0xb5, 0x48, 0xd0,
	0xc0, 0x7a, 0xcc, 0xd4, 0xc4, 0x87, 0xc1, 0x1b, 0x2a, 0xc5, 0xd3, 0x76, 0xba, 0xb6, 0x25, 0x14,
	0x06, 0x09, 0x6a, 0x9e, 0xe5, 0xfb, 0xe9, 0xdc, 0x93, 0x2f, 0xb5, 0xa6, 0x58, 0xc2, 0x1f, 0x9b,
	0xc8, 0x12, 0x65, 0x9d, 0xad, 0x91, 0x70, 0x20, 0x5f, 0x83, 0x22, 0x93, 0xdf, 0xe4, 0x18, 0x5c,
	0xfc, 0xe0, 0xb2, 0x3f, 0x3d, 0x9f, 0xbc, 0x84, 0x94, 0x46, 0x2a, 0x4b, 0x70, 0x9b, 0xed, 0xae,
	0xcd, 0x5c, 0x87, 0xce, 0x02, 0xa2, 0x7a, 0xb6, 0xea, 0x1b, 0xe1, 0xe6, 0x23, 0x00, 0x00, 0xff,
	0xff, 0xae, 0x3f, 0x5b, 0x13, 0x75, 0x02, 0x00, 0x00,
}
